add_compile_options(
        -Waddress
        -Wformat-nonliteral
        -Wformat-security
        -Wformat
        -Winit-self
        -Wmissing-include-dirs
        -Wno-multichar
        -Wno-parentheses
        -Wno-type-limits
        -Wno-unused-parameter
        -Wno-unused-variable
        -Wunreachable-code
        -Wwrite-strings
        -Wpointer-arith
        -Werror
        -Wall
        -Wextra
        -Wpedantic
)
